repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        require_serial: true
      - id: darglint
        name: darglint
        entry: darglint
        language: system
        types: [python]
        stages: [manual]
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        require_serial: true
      - id: isort
        name: isort
        entry: isort
        require_serial: true
        language: system
        types_or: [cython, pyi, python]
        args: ["--filter-files"]
      - id: pyupgrade
        name: pyupgrade
        description: Automatically upgrade syntax for newer versions.
        entry: pyupgrade
        language: system
        types: [python]
        args: [--py37-plus]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
